version: '2'
services:
  nginx:
    hostname: NGINX
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: ./Dockerfile
      args:
        - domain=${domain}
    volumes:
      - ./cert/:/etc/nginx/cert/
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "8443:8443"
    networks: 
      vpn:
        ipv4_address: 172.168.22.2
    restart: on-failure

  trojan:
    hostname: TROJAN
    container_name: trojan
    build: 
      context: ./trojan
      dockerfile: ./Dockerfile
      args:
        - password=${password}
    volumes:
      - ./cert/:/usr/local/etc/trojan/cert/
    ports:
      - "443:443"
    networks: 
      vpn:
        ipv4_address: 172.168.22.3
    depends_on: 
      - nginx
    restart: on-failure

  
networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.22.0/24
          gateway: 172.168.22.1
